http:
  routers:
    proyecto-demo-2:
      rule: "PathPrefix(`/proyecto-demo-2`)"
      service: proyecto-demo-2
  services:
    proyecto-demo-2:
      loadBalancer:
        servers:
          - url: "http://dashboard-proyecto-demo-2:8501"
