-- ============================================================================
-- ESQUEMA PRINCIPAL PARA SAACDATA - PostgreSQL 17
-- Basado en:
--   - dbdiagram.txt
--   - BaseParaPropiedad.sql
--   - CSV definitivos T_OTRI_PI_*
-- Decisión:
--   - Se respetan nombres de tablas/columnas de los CSV
--   - Campos pesados de referencias se dejan nullable
--   - Se agrega modelo de archivos raw en MinIO
-- ============================================================================

BEGIN;

-- ============================================================================
-- TABLA DE ESTADOS
-- ============================================================================

CREATE TABLE IF NOT EXISTS "T_OTRI_PI_ESTADOS" (
    "IDOTRIPIESTADOS" integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "DESCRIPCION" varchar(255) NOT NULL,
    "ULTIMO_CAMBIO" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS "UX_T_OTRI_PI_ESTADOS_DESCRIPCION"
    ON "T_OTRI_PI_ESTADOS" ("DESCRIPCION");

-- ============================================================================
-- TABLA DE PARÁMETROS
-- ============================================================================

CREATE TABLE IF NOT EXISTS "T_OTRI_PI_PARAMETROS" (
    "IDOTRIPIPARAMETROS" integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "RESULTADOMAXIMO" integer,
    "OBVIEDADMINREF" integer,
    "NUMEROTOPK" integer NOT NULL,
    "UMBRALNOVEDAD" numeric(5,4),
    "RANGOINFERIOR" numeric(5,4),
    "RANGOSUPERIOR" numeric(5,4),
    "UMBRALOBVIEDADMEDIA" numeric(5,4),
    "UMBRALOBVIEDADMULREF" numeric(5,4),
    "NOMBREMODELO" varchar(255),
    "FECHACREACION" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ULTIMO_CAMBIO" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "CK_T_OTRI_PI_PARAMETROS_NUMEROTOPK"
        CHECK ("NUMEROTOPK" >= 0),
    CONSTRAINT "CK_T_OTRI_PI_PARAMETROS_RESULTADOMAXIMO"
        CHECK ("RESULTADOMAXIMO" IS NULL OR "RESULTADOMAXIMO" >= 0)
);

-- ============================================================================
-- TABLAS DE ANÁLISIS
-- ============================================================================

CREATE TABLE IF NOT EXISTS "T_OTRI_PI_NOVEDAD" (
    "IDOTRIPINOVEDAD" integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "IDOTRIPIESTADOS" integer NOT NULL,
    "RIESGO" integer NOT NULL,
    "MAXIMASIMILITUD" numeric(8,6) NOT NULL,
    "PUNTAJENOVEDAD" numeric(8,6) NOT NULL,
    "UMBRALNNONOVEDADALTO" numeric(5,4) NOT NULL,
    "UMBRALZONAGRISBAJO" numeric(5,4) NOT NULL,
    "FECHACREACION" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ULTIMO_CAMBIO" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "FK_T_OTRI_PI_NOVEDAD_ESTADOS"
        FOREIGN KEY ("IDOTRIPIESTADOS")
        REFERENCES "T_OTRI_PI_ESTADOS" ("IDOTRIPIESTADOS"),
    CONSTRAINT "CK_T_OTRI_PI_NOVEDAD_RIESGO"
        CHECK ("RIESGO" BETWEEN 1 AND 3)
);

CREATE TABLE IF NOT EXISTS "T_OTRI_PI_INVENTIVO" (
    "IDOTRIPIINVENTIVO" integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "IDOTRIPIESTADOS" integer NOT NULL,
    "RIESGO" integer NOT NULL,
    "MEDIASIMILITUDTOPK" numeric(8,6),
    "NUMEROREFFUERTES" integer,
    "GRUPOSCPCUNICOS" text,
    "DESCRIPCION" varchar(255),
    "FECHACREACION" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ULTIMO_CAMBIO" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "FK_T_OTRI_PI_INVENTIVO_ESTADOS"
        FOREIGN KEY ("IDOTRIPIESTADOS")
        REFERENCES "T_OTRI_PI_ESTADOS" ("IDOTRIPIESTADOS"),
    CONSTRAINT "CK_T_OTRI_PI_INVENTIVO_RIESGO"
        CHECK ("RIESGO" BETWEEN 1 AND 3),
    CONSTRAINT "CK_T_OTRI_PI_INVENTIVO_NUMREF"
        CHECK ("NUMEROREFFUERTES" IS NULL OR "NUMEROREFFUERTES" >= 0)
);

CREATE TABLE IF NOT EXISTS "T_OTRI_PI_INDUSTRIAL" (
    "IDOTRIPIINDUSTRIAL" integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "IDOTRIPIESTADOS" integer NOT NULL,
    "PALABRACLAVEEVIDEN" text,
    "SECCIONESCPCPRINCI" text,
    "GRUPOSCPCPRINCI" text,
    "ETIQUETASESUGERI" text,
    "FECHACREACION" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ULTIMO_CAMBIO" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "FK_T_OTRI_PI_INDUSTRIAL_ESTADOS"
        FOREIGN KEY ("IDOTRIPIESTADOS")
        REFERENCES "T_OTRI_PI_ESTADOS" ("IDOTRIPIESTADOS")
);

CREATE TABLE IF NOT EXISTS "T_OTRI_PI_INDUSTRIAL_LLM" (
    "IDOTRIPIINDUSTRIALLLM" integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "IDOTRIPIESTADOS" integer NOT NULL,
    "CONFIANZA" numeric(3,2),
    "FRASESEVIDENCIA" text,
    "INFORMACIONFALTANTE" text,
    "ETIQUETASINDUSSUGE" text,
    "NOTASEN" text,
    "NOTASES" text,
    "FECHACREACION" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ULTIMO_CAMBIO" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "FK_T_OTRI_PI_INDUSTRIAL_LLM_ESTADOS"
        FOREIGN KEY ("IDOTRIPIESTADOS")
        REFERENCES "T_OTRI_PI_ESTADOS" ("IDOTRIPIESTADOS"),
    CONSTRAINT "CK_T_OTRI_PI_INDUSTRIAL_LLM_CONFIANZA"
        CHECK ("CONFIANZA" IS NULL OR ("CONFIANZA" >= 0 AND "CONFIANZA" <= 1))
);

-- ============================================================================
-- MÓDULOS
-- ============================================================================

CREATE TABLE IF NOT EXISTS "T_OTRI_PI_MODULOS" (
    "IDOTRIPIMODULOS" integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "IDOTRIPINOVEDAD" integer NOT NULL,
    "IDOTRIPIINVENTIVO" integer NOT NULL,
    "IDOTRIPIESTADOS" integer NOT NULL,
    "IDOTRIPIINDUSTRIAL" integer NOT NULL,
    "IDOTRIPIINDUSTRIALLLM" integer NOT NULL,
    "FECHACREACION" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ULTIMO_CAMBIO" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "FK_T_OTRI_PI_MODULOS_NOVEDAD"
        FOREIGN KEY ("IDOTRIPINOVEDAD")
        REFERENCES "T_OTRI_PI_NOVEDAD" ("IDOTRIPINOVEDAD"),
    CONSTRAINT "FK_T_OTRI_PI_MODULOS_INVENTIVO"
        FOREIGN KEY ("IDOTRIPIINVENTIVO")
        REFERENCES "T_OTRI_PI_INVENTIVO" ("IDOTRIPIINVENTIVO"),
    CONSTRAINT "FK_T_OTRI_PI_MODULOS_ESTADOS"
        FOREIGN KEY ("IDOTRIPIESTADOS")
        REFERENCES "T_OTRI_PI_ESTADOS" ("IDOTRIPIESTADOS"),
    CONSTRAINT "FK_T_OTRI_PI_MODULOS_INDUSTRIAL"
        FOREIGN KEY ("IDOTRIPIINDUSTRIAL")
        REFERENCES "T_OTRI_PI_INDUSTRIAL" ("IDOTRIPIINDUSTRIAL"),
    CONSTRAINT "FK_T_OTRI_PI_MODULOS_INDUSTRIAL_LLM"
        FOREIGN KEY ("IDOTRIPIINDUSTRIALLLM")
        REFERENCES "T_OTRI_PI_INDUSTRIAL_LLM" ("IDOTRIPIINDUSTRIALLLM")
);

-- ============================================================================
-- PROCESO
-- ============================================================================

CREATE TABLE IF NOT EXISTS "T_OTRI_PI_PROCESO" (
    "IDOTRIPIPROCESO" integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "IDPERSONA" integer NOT NULL,
    "RESUMEN" text,
    "MENSAJEERROR" text,
    "PROGRESO" integer NOT NULL DEFAULT 0,
    "IDTAREA" varchar(50) NOT NULL,
    "TITULO" varchar(500) NOT NULL,
    "IDOTRIPIESTADOS" integer NOT NULL,
    "PASOACTUAL" varchar(100),
    "FECHACREACION" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "FECHAACTUALIZACION" timestamp(6),
    "FECHAFIN" timestamp(6),
    "ULTIMO_CAMBIO" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "FK_T_OTRI_PI_PROCESO_ESTADOS"
        FOREIGN KEY ("IDOTRIPIESTADOS")
        REFERENCES "T_OTRI_PI_ESTADOS" ("IDOTRIPIESTADOS"),
    CONSTRAINT "UX_T_OTRI_PI_PROCESO_IDTAREA"
        UNIQUE ("IDTAREA"),
    CONSTRAINT "CK_T_OTRI_PI_PROCESO_PROGRESO"
        CHECK ("PROGRESO" BETWEEN 0 AND 100)
);

-- ============================================================================
-- MAESTRO DE REFERENCIAS RAW EN MINIO
-- Un registro puede representar:
--   - un solo archivo consolidado
--   - un conjunto de archivos separados
-- ============================================================================

CREATE TABLE IF NOT EXISTS "T_OTRI_PI_REFERENCIAS_RAW" (
    "IDOTRIPIREFERENCIASRAW" integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "IDOTRIPIPROCESO" integer NOT NULL,
    "MODOALMACENAMIENTO" varchar(20) NOT NULL,
    "STORAGE_PROVIDER" varchar(20) NOT NULL DEFAULT 'MINIO',
    "BUCKET_BASE" varchar(255),
    "PREFIJO_BASE" text,
    "FORMATO_PREFERIDO" varchar(20),
    "DESCRIPCION" text,
    "METADATA" jsonb,
    "FECHACREACION" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ULTIMO_CAMBIO" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "FK_T_OTRI_PI_REFERENCIAS_RAW_PROCESO"
        FOREIGN KEY ("IDOTRIPIPROCESO")
        REFERENCES "T_OTRI_PI_PROCESO" ("IDOTRIPIPROCESO")
        ON DELETE CASCADE,
    CONSTRAINT "CK_T_OTRI_PI_REFERENCIAS_RAW_MODO"
        CHECK ("MODOALMACENAMIENTO" IN ('CONSOLIDADO', 'SEPARADO')),
    CONSTRAINT "CK_T_OTRI_PI_REFERENCIAS_RAW_PROVIDER"
        CHECK ("STORAGE_PROVIDER" IN ('MINIO')),
    CONSTRAINT "CK_T_OTRI_PI_REFERENCIAS_RAW_FORMATO"
        CHECK (
            "FORMATO_PREFERIDO" IS NULL
            OR "FORMATO_PREFERIDO" IN ('csv', 'txt', 'parquet', 'json')
        )
);

-- ============================================================================
-- RESPUESTA
-- Las 3 columnas pesadas se mantienen nullable por compatibilidad.
-- La referencia principal al raw externo se hace por IDOTRIPIREFERENCIASRAW.
-- ============================================================================

CREATE TABLE IF NOT EXISTS "T_OTRI_PI_RESPUESTA" (
    "IDOTRIPIRESPUESTA" integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "IDOTRIPIPROCESO" integer NOT NULL,
    "IDOTRIPIPARAMETROS" integer NOT NULL,
    "IDOTRIPIMODULOS" integer NOT NULL,
    "IDOTRIPIREFERENCIASRAW" integer,
    "REFERENCPRINCIPALES" text NULL,
    "REFERENCIAARTICULOS" text NULL,
    "REFERENCIASPATENTES" text NULL,
    "MARCATIEMPOISO" varchar(50),
    "FECHACREACION" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ULTIMO_CAMBIO" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "FK_T_OTRI_PI_RESPUESTA_PROCESO"
        FOREIGN KEY ("IDOTRIPIPROCESO")
        REFERENCES "T_OTRI_PI_PROCESO" ("IDOTRIPIPROCESO"),
    CONSTRAINT "FK_T_OTRI_PI_RESPUESTA_PARAMETROS"
        FOREIGN KEY ("IDOTRIPIPARAMETROS")
        REFERENCES "T_OTRI_PI_PARAMETROS" ("IDOTRIPIPARAMETROS"),
    CONSTRAINT "FK_T_OTRI_PI_RESPUESTA_MODULOS"
        FOREIGN KEY ("IDOTRIPIMODULOS")
        REFERENCES "T_OTRI_PI_MODULOS" ("IDOTRIPIMODULOS"),
    CONSTRAINT "FK_T_OTRI_PI_RESPUESTA_REFERENCIAS_RAW"
        FOREIGN KEY ("IDOTRIPIREFERENCIASRAW")
        REFERENCES "T_OTRI_PI_REFERENCIAS_RAW" ("IDOTRIPIREFERENCIASRAW"),
    CONSTRAINT "UX_T_OTRI_PI_RESPUESTA_PROCESO"
        UNIQUE ("IDOTRIPIPROCESO")
);

-- ============================================================================
-- DETALLE DE ARCHIVOS RAW
-- Permite 1 archivo consolidado o varios archivos por tipo.
-- ============================================================================

CREATE TABLE IF NOT EXISTS "T_OTRI_PI_REFERENCIAS_RAW_DETALLE" (
    "IDOTRIPIREFERENCIASRAWDET" integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "IDOTRIPIREFERENCIASRAW" integer NOT NULL,
    "TIPO_CONTENIDO" varchar(20) NOT NULL,
    "BUCKET" varchar(255) NOT NULL,
    "OBJECT_KEY" text NOT NULL,
    "FORMATO_ARCHIVO" varchar(20) NOT NULL,
    "NOMBRE_ARCHIVO" varchar(500),
    "MIME_TYPE" varchar(100),
    "TAMANIO_BYTES" bigint,
    "ETAG" varchar(128),
    "VERSION_ID" varchar(255),
    "CHECKSUM_SHA256" char(64),
    "ORDEN" smallint NOT NULL DEFAULT 1,
    "ACTIVO" boolean NOT NULL DEFAULT true,
    "METADATA" jsonb,
    "FECHACREACION" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ULTIMO_CAMBIO" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "FK_T_OTRI_PI_REFERENCIAS_RAW_DETALLE_RAW"
        FOREIGN KEY ("IDOTRIPIREFERENCIASRAW")
        REFERENCES "T_OTRI_PI_REFERENCIAS_RAW" ("IDOTRIPIREFERENCIASRAW")
        ON DELETE CASCADE,
    CONSTRAINT "CK_T_OTRI_PI_REFERENCIAS_RAW_DETALLE_TIPO"
        CHECK ("TIPO_CONTENIDO" IN ('CONSOLIDADO', 'PRINCIPALES', 'ARTICULOS', 'PATENTES')),
    CONSTRAINT "CK_T_OTRI_PI_REFERENCIAS_RAW_DETALLE_FORMATO"
        CHECK ("FORMATO_ARCHIVO" IN ('csv', 'txt', 'parquet', 'json')),
    CONSTRAINT "CK_T_OTRI_PI_REFERENCIAS_RAW_DETALLE_TAMANIO"
        CHECK ("TAMANIO_BYTES" IS NULL OR "TAMANIO_BYTES" >= 0),
    CONSTRAINT "UX_T_OTRI_PI_REFERENCIAS_RAW_DETALLE_OBJETO"
        UNIQUE ("IDOTRIPIREFERENCIASRAW", "BUCKET", "OBJECT_KEY"),
    CONSTRAINT "UX_T_OTRI_PI_REFERENCIAS_RAW_DETALLE_ORDEN"
        UNIQUE ("IDOTRIPIREFERENCIASRAW", "TIPO_CONTENIDO", "ORDEN")
);

-- ============================================================================
-- ÍNDICES DE APOYO
-- ============================================================================

CREATE INDEX IF NOT EXISTS "IX_T_OTRI_PI_PROCESO_IDOTRIPIESTADOS"
    ON "T_OTRI_PI_PROCESO" ("IDOTRIPIESTADOS");

CREATE INDEX IF NOT EXISTS "IX_T_OTRI_PI_RESPUESTA_IDOTRIPIPARAMETROS"
    ON "T_OTRI_PI_RESPUESTA" ("IDOTRIPIPARAMETROS");

CREATE INDEX IF NOT EXISTS "IX_T_OTRI_PI_RESPUESTA_IDOTRIPIMODULOS"
    ON "T_OTRI_PI_RESPUESTA" ("IDOTRIPIMODULOS");

CREATE INDEX IF NOT EXISTS "IX_T_OTRI_PI_RESPUESTA_IDOTRIPIREFERENCIASRAW"
    ON "T_OTRI_PI_RESPUESTA" ("IDOTRIPIREFERENCIASRAW");

CREATE INDEX IF NOT EXISTS "IX_T_OTRI_PI_MODULOS_IDOTRIPIESTADOS"
    ON "T_OTRI_PI_MODULOS" ("IDOTRIPIESTADOS");

CREATE INDEX IF NOT EXISTS "IX_T_OTRI_PI_NOVEDAD_IDOTRIPIESTADOS"
    ON "T_OTRI_PI_NOVEDAD" ("IDOTRIPIESTADOS");

CREATE INDEX IF NOT EXISTS "IX_T_OTRI_PI_INVENTIVO_IDOTRIPIESTADOS"
    ON "T_OTRI_PI_INVENTIVO" ("IDOTRIPIESTADOS");

CREATE INDEX IF NOT EXISTS "IX_T_OTRI_PI_INDUSTRIAL_IDOTRIPIESTADOS"
    ON "T_OTRI_PI_INDUSTRIAL" ("IDOTRIPIESTADOS");

CREATE INDEX IF NOT EXISTS "IX_T_OTRI_PI_INDUSTRIAL_LLM_IDOTRIPIESTADOS"
    ON "T_OTRI_PI_INDUSTRIAL_LLM" ("IDOTRIPIESTADOS");

CREATE INDEX IF NOT EXISTS "IX_T_OTRI_PI_REFERENCIAS_RAW_IDOTRIPIPROCESO"
    ON "T_OTRI_PI_REFERENCIAS_RAW" ("IDOTRIPIPROCESO");

CREATE INDEX IF NOT EXISTS "IX_T_OTRI_PI_REFERENCIAS_RAW_DETALLE_TIPO"
    ON "T_OTRI_PI_REFERENCIAS_RAW_DETALLE" ("TIPO_CONTENIDO");

-- ============================================================================
-- COMENTARIOS ÚTILES
-- ============================================================================

COMMENT ON TABLE "T_OTRI_PI_REFERENCIAS_RAW" IS
'Catálogo maestro de referencias crudas almacenadas en MinIO. Puede representar un archivo consolidado o varios archivos separados.';

COMMENT ON TABLE "T_OTRI_PI_REFERENCIAS_RAW_DETALLE" IS
'Detalle físico de los objetos en MinIO para referencias principales, artículos, patentes o consolidado.';

COMMENT ON COLUMN "T_OTRI_PI_RESPUESTA"."REFERENCPRINCIPALES" IS
'Se mantiene nullable por compatibilidad; idealmente se externaliza a MinIO.';

COMMENT ON COLUMN "T_OTRI_PI_RESPUESTA"."REFERENCIAARTICULOS" IS
'Se mantiene nullable por compatibilidad; idealmente se externaliza a MinIO.';

COMMENT ON COLUMN "T_OTRI_PI_RESPUESTA"."REFERENCIASPATENTES" IS
'Se mantiene nullable por compatibilidad; idealmente se externaliza a MinIO.';

COMMENT ON COLUMN "T_OTRI_PI_RESPUESTA"."IDOTRIPIREFERENCIASRAW" IS
'FK al catálogo maestro de archivos raw en MinIO.';

COMMIT;